<a href="https://colab.research.google.com/github/ahcamachod/2207-clasificacion-optimizando-modelos-de-machine-learning/blob/aula-2/clasificacion_morosos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

datos = pd.read_csv('/content/morosos.csv')
datos.head()

,ingresos,prestamo_anual,anos_casa_propia,telefono_trabajo,calificacion_ciudad,score_1,score_2,score_3,score_social,cambio_telefono,moroso
0,16855.246324,2997.000000,12.157324,0,2.0,0.501213,0.003109,0.513171,0.117428,243.0,1
1,13500.000000,2776.050000,12.157324,0,2.0,0.501213,0.269730,0.513171,0.097900,617.0,0
2,11250.000000,2722.188351,12.157324,0,3.0,0.701396,0.518625,0.700184,0.118600,9.0,0
3,27000.000000,6750.000000,3.000000,0,2.0,0.501213,0.649571,0.513171,0.047400,300.0,0
4,22500.000000,3097.800000,12.157324,0,2.0,0.440744,0.509677,0.513171,0.014400,2913.0,1

In [2]:
datos.shape

(14578, 11)

In [3]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14578 entries, 0 to 14577
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ingresos             14578 non-null  float64
 1   prestamo_anual       14578 non-null  float64
 2   anos_casa_propia     14578 non-null  float64
 3   telefono_trabajo     14578 non-null  int64
 4   calificacion_ciudad  14578 non-null  float64
 5   score_1              14578 non-null  float64
 6   score_2              14578 non-null  float64
 7   score_3              14578 non-null  float64
 8   score_social         14578 non-null  float64
 9   cambio_telefono      14578 non-null  float64
 10  moroso               14578 non-null  int64
dtypes: float64(9), int64(2)
memory usage: 1.2 MB

In [4]:
round(datos.moroso.value_counts(normalize=True)*100,2)

moroso
0    67.65
1    32.35
Name: proportion, dtype: float64

In [5]:
from sklearn.model_selection import train_test_split

X = datos.drop('moroso',axis=1)
y = datos.moroso
seed = 42

X, X_test, y, y_test = train_test_split(X,y,test_size=0.15,random_state=seed, stratify=y)
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.33,random_state=seed, stratify=y)

### Documentación oficial del Árbol de Decisión en SK-Learn
https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

In [6]:
from sklearn.tree import DecisionTreeClassifier

modelo_dt = DecisionTreeClassifier(max_depth=3, random_state=seed)
modelo_dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [7]:
from sklearn.metrics import recall_score

y_pred = modelo_dt.predict(X_val)
recall_dt = recall_score(y_val, y_pred)
print(f'La sensibilidad (recall) del modelo de Árbol de Decisión (dt) es de: {recall_dt*100:.3f}%')

La sensibilidad (recall) del modelo de Árbol de Decisión (dt) es de: 14.588%

### Documentación oficial de la Regresión Logística en SK-Learn
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

logistic_pipeline = make_pipeline(StandardScaler(),LogisticRegression())
logistic_pipeline.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [9]:
y_pred = logistic_pipeline.predict(X_val)
recall_lr = recall_score(y_val, y_pred)
print(f'La sensibilidad (recall) del modelo de Regresión Logística (lr) es de: {recall_lr*100:.3f}%')

La sensibilidad (recall) del modelo de Regresión Logística (lr) es de: 26.531%